### ISSUE TITLE
Building fails on Ubuntu 16.04/Raspberry Pi

### ISSUE THREAD

**Issue by jeffehobbs** [n3mo/massmine#10]
After installing chicken-install and all dependencies, deploy.sh fails:

```
Error: cannot create directory: a file with the same name already exists


Error: shell command terminated with nonzero exit code
17920
"'/usr/bin/csi' -bnq -e \"(require-library setup-api)\" -e \"(import setup-api)\"...
./deploy.sh: line 59: ./massmine/massmine: Not a directory
	zip warning: name not matched: ./massmine/

zip error: Nothing to do! (try: zip -r massmine--linux-x86_64.zip . -i ./massmine/)
./deploy.sh: line 61: ./massmine/massmine: Not a directory
./deploy.sh: line 64: ./massmine/massmine: Not a directory
mv: cannot stat 'massmine--linux-x86_64.zip': No such file or directory
./deploy.sh: line 65: ./massmine/massmine: Not a directory
```

**Comment by n3mo** [comment]
Apologies for the delayed response--I was traveling this past week.

I'm excited to see someone trying to build massmine on a Pi, as this has been on my own personal todo list for some time. The build script deploy.sh (despite being included in the repo) wasn't really intended for mainstream consumption. I use it to generate the pre-built binaries that are available at [massmine.org](http://www.massmine.org/docs/install.html), and some aspects of it (particularly the code for compiling on OS X) assume additional features unique to my machine.

If you just want to build an executable for your own Raspberry Pi, it should be much easier. From within the root folder of the cloned repo you can run:

```sh
csc massmine.scm
```
That will create a single executable called `massmine`. Put that executable on your path and you should be ready to go.

If you haven't already done so, you'll need to install the necessary Chicken packages prior to compiling massmine. That can be done with:

```sh
chicken-install clucker args openssl medea srfi-19 pathname-expand html-parser
```

However, if I've misunderstood and you do want to build a distributable binary bundle using (something like) the deploy.sh script, let me know and I'll be happy to help out.

Also, please share your experience (success or failure). I'm interested in your experience with both Ubuntu 16.04 and Raspberry Pi.

Cheers

**Comment by n3mo** [comment]
Any luck? I'm hoping to close this issue but I'd prefer to get things working for you.

**Comment by jeffehobbs** [comment]
I still get a pile of cryptic errors, to be honest, while installing the Chicken packages. I've tried as the regular user and the superuser and still no.
```openssl.c:33:25: fatal error: openssl/err.h: No such file or directory
compilation terminated.

Error: shell command terminated with non-zero exit status 256: 'gcc' 'openssl.c' -o 'openssl.o' -c  -fno-strict-aliasing -fwrapv -DHAVE_CHICKEN_CONFIG_H -DC_ENABLE_PTABLES -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -DPIC -DC_SHARED -I"/usr/include/chicken"

Error: shell command failed with nonzero exit status 256:

  '/usr/bin/csc' -feature compiling-extension -setup-mode    -O2 -d0 -s -j openssl openssl.scm -lssl -lcrypto


Error: shell command terminated with nonzero exit code
17920
"'/usr/bin/csi' -bnq -setup-mode -e \"(require-library setup-api)\" -e \"(import...
jeff@raspberry1:~/massmine$ ```

**Comment by n3mo** [comment]
I believe this error is triggered during the installation of the openssl egg. I believe to build successfully, you'll need to install the openssl development libraries (Ubuntu package `libssl-dev`) in your system beforehand. It should be available for your version of Ubuntu:

```sh
sudo apt-get install libssl-dev
```

Assuming that works, try building massmine again. It should resolve at least the current error you're getting...

**Comment by jeffehobbs** [comment]
Hey! THAT WORKED. Tested and verified with Google Trends API call. With libssl-dev and the above chicken-install packages, Massmine compiles fine on the Raspberry Pi/Ubuntu 16.04.

**Comment by jeffehobbs** [comment]
(Thanks, man!)

**Comment by n3mo** [comment]
Excellent news! I'm glad to hear that we got it working, and that it seems to be running on your setup. I have some new data sources for massmine in the works for the near future, and I'm working on a tool (tentatively called [mmtool](https://github.com/n3mo/mmtool)) that provides both command line AND and a web-app-style graphical interface for both collecting data with massmine, and exploring/analyzing the results.

I'll update the [build instructions](http://www.massmine.org/docs/install.html) to include `libssl-dev`. Thanks for the feedback-- I hope the tool proves to be useful for you :)
